const ACTIONSTYPES = {
  ADD_ITEM: "ADD_ITEM",
  CANCEL_EDIT_ITEM: "CANCEL_EDIT_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  ITEM_COMPLETION: "ITEM_COMPLETION",
  SELECT_EDIT_ITEM: "SELECT_EDIT_ITEM",
};

export default ACTIONSTYPES;
